site_name: Py3fun Docs
site_url: https://py3fun.github.io
repo_url: https://github.com/py3fun/py3fun.github.io

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md
  - 关于: about.md


