site_name: Py3fun Docs
site_url: https://py3fun.github.io
repo_url: https://github.com/py3fun/py3fun.github.io

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md
  - 关于: about.md
  - 指南:
    - 快速开始: guide/getting-started.md
    - 安装说明: guide/installation.md
    - 配置说明: guide/configuration.md
  - 教程:
    - 基础教程: tutorials/basic-tutorial.md
    - 高级教程: tutorials/advanced-tutorial.md
    - 实例代码: tutorials/examples.md
  - API 文档:
    - 概览: api/overview.md
    - 函数: api/functions.md
    - 类: api/classes.md
  - 博客:
    - 最新文章: blog/latest.md
    - 文章归档: blog/archive.md


